/**
 * KuzuDB SQL Generator
 *
 * Phase 2.2: Schema Compiler
 *
 * Generates KuzuDB CREATE TABLE statements from schema AST
 */

import {
  SchemaAST,
  EntityNode,
  RelationshipNode,
  FieldNode,
  FieldType,
} from "../types.js";

export class SQLGenerator {
  generate(ast: SchemaAST): string {
    let output = this.generateHeader(ast);

    // Generate entity tables
    output += "-- Entity Tables\n\n";
    for (const entity of Object.values(ast.entities)) {
      output += this.generateEntityTable(entity);
      output += "\n\n";
    }

    // Generate relationship tables
    if (ast.relationships && Object.keys(ast.relationships).length > 0) {
      output += "-- Relationship Tables\n\n";
      for (const rel of Object.values(ast.relationships)) {
        output += this.generateRelationshipTable(rel);
        output += "\n\n";
      }
    }

    // Generate indexes
    output += this.generateIndexes(ast);

    return output;
  }

  private generateHeader(ast: SchemaAST): string {
    return `-- Generated KuzuDB SQL Schema
-- 
-- Schema: ${ast.name}
-- Version: ${ast.version}${
      ast.description ? `\n-- Description: ${ast.description}` : ""
    }
-- 
-- This file is auto-generated by @relish/schema-compiler
-- DO NOT EDIT MANUALLY

`;
  }

  private generateEntityTable(entity: EntityNode): string {
    const lines: string[] = [];

    if (entity.description) {
      lines.push(`-- ${entity.description}`);
    }

    const fields = entity.fields.map((f) => this.mapFieldToSQL(f));
    const primaryKey = entity.fields.find(
      (f) => f.name === "id" || f.name === "ID"
    );

    if (primaryKey) {
      lines.push(`CREATE NODE TABLE ${entity.name}(`);
      lines.push(`  ${fields.join(",\n  ")},`);
      lines.push(`  PRIMARY KEY(${primaryKey.name})`);
      lines.push(`);`);
    } else {
      // No explicit primary key, use first field
      const pkField = entity.fields[0];
      lines.push(`CREATE NODE TABLE ${entity.name}(`);
      lines.push(`  ${fields.join(",\n  ")},`);
      lines.push(`  PRIMARY KEY(${pkField.name})`);
      lines.push(`);`);
    }

    return lines.join("\n");
  }

  private generateRelationshipTable(rel: RelationshipNode): string {
    const lines: string[] = [];

    if (rel.description) {
      lines.push(`-- ${rel.description}`);
    }

    if (rel.properties && rel.properties.length > 0) {
      const props = rel.properties.map((p) => this.mapFieldToSQL(p));
      lines.push(
        `CREATE REL TABLE ${rel.name}(FROM ${rel.from} TO ${
          rel.to
        }, ${props.join(", ")});`
      );
    } else {
      lines.push(
        `CREATE REL TABLE ${rel.name}(FROM ${rel.from} TO ${rel.to});`
      );
    }

    return lines.join("\n");
  }

  private generateIndexes(ast: SchemaAST): string {
    const lines: string[] = ["-- Indexes\n"];
    let hasIndexes = false;

    for (const entity of Object.values(ast.entities)) {
      // Unique field indexes
      const uniqueFields = entity.fields.filter((f) => f.unique);
      for (const field of uniqueFields) {
        lines.push(
          `-- CREATE INDEX idx_${entity.name}_${field.name}_unique ON ${entity.name}(${field.name});`
        );
        hasIndexes = true;
      }

      // Custom indexes
      if (entity.indexes) {
        for (const index of entity.indexes) {
          const indexName = `idx_${entity.name}_${index.fields.join("_")}`;
          lines.push(
            `-- CREATE INDEX ${indexName} ON ${entity.name}(${index.fields.join(
              ", "
            )});`
          );
          hasIndexes = true;
        }
      }
    }

    if (!hasIndexes) {
      return "-- No indexes defined\n";
    }

    lines.push(
      "\n-- Note: KuzuDB indexes are created automatically on primary keys"
    );
    lines.push(
      "-- Additional indexes commented out - verify KuzuDB support before uncommenting"
    );

    return lines.join("\n");
  }

  private mapFieldToSQL(field: FieldNode): string {
    const sqlType = this.mapFieldTypeToSQL(field.type);
    const notNull = field.required ? " NOT NULL" : "";
    return `${field.name} ${sqlType}${notNull}`;
  }

  private mapFieldTypeToSQL(type: FieldType): string {
    switch (type) {
      case "string":
      case "enum":
        return "STRING";
      case "number":
        return "DOUBLE";
      case "integer":
        return "INT64";
      case "boolean":
        return "BOOLEAN";
      case "date":
        return "DATE";
      case "timestamp":
        return "TIMESTAMP";
      case "json":
        return "STRING"; // KuzuDB stores JSON as STRING
      default:
        return "STRING";
    }
  }
}
