/**
 * TypeScript Type Generator
 *
 * Phase 2.2: Schema Compiler
 *
 * Generates TypeScript interfaces from schema AST
 */

import { SchemaAST, EntityNode, FieldNode, FieldType } from "../types.js";

export class TypeGenerator {
  generate(ast: SchemaAST): string {
    let output = this.generateHeader(ast);

    // Generate entity interfaces
    for (const entity of Object.values(ast.entities)) {
      output += this.generateEntityInterface(entity);
      output += "\n\n";
    }

    // Generate schema types object
    output += this.generateSchemaTypes(ast);

    return output;
  }

  private generateHeader(ast: SchemaAST): string {
    return `/**
 * Generated TypeScript Types
 * 
 * Schema: ${ast.name}
 * Version: ${ast.version}${
      ast.description ? `\n * Description: ${ast.description}` : ""
    }
 * 
 * This file is auto-generated by @relish/schema-compiler
 * DO NOT EDIT MANUALLY
 */

`;
  }

  private generateEntityInterface(entity: EntityNode): string {
    const lines: string[] = [];

    if (entity.description) {
      lines.push(`/**`);
      lines.push(` * ${entity.description}`);
      lines.push(` */`);
    }

    lines.push(`export interface ${entity.name} {`);

    for (const field of entity.fields) {
      if (field.description) {
        lines.push(`  /** ${field.description} */`);
      }

      const optional = field.required ? "" : "?";
      const type = this.mapFieldType(field);
      lines.push(`  ${field.name}${optional}: ${type};`);
    }

    lines.push(`}`);

    return lines.join("\n");
  }

  private generateSchemaTypes(ast: SchemaAST): string {
    const entityNames = Object.keys(ast.entities);

    return `/**
 * Schema type definitions
 */
export type EntityType = ${entityNames.map((n) => `'${n}'`).join(" | ")};

export interface SchemaTypes {
${entityNames.map((name) => `  ${name}: ${name};`).join("\n")}
}

export type Entity = ${entityNames.join(" | ")};
`;
  }

  private mapFieldType(field: FieldNode): string {
    if (field.enum) {
      return field.enum.map((v) => `'${v}'`).join(" | ");
    }

    switch (field.type) {
      case "string":
        return "string";
      case "number":
      case "integer":
        return "number";
      case "boolean":
        return "boolean";
      case "date":
      case "timestamp":
        return "Date | string";
      case "json":
        return "Record<string, any>";
      default:
        return "any";
    }
  }
}
